# Setup
title:        Cafe Latte
tagline:      MN Lee's Personal Blog
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       MN Lee
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown