# Setup
title:        MN Lee's IT Blog
tagline:      MN Lee's IT Blog
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       MN Lee
  url:        https://github.com/mee-nam-lee/ 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown